### ISSUE TITLE
signup middleware is called twice and creating an issue with database duplicate record creation

### ISSUE THREAD

**Issue by abslanka** [rucken/todo-nestjs#2]
signup middleware is called twice and creating an issue with database duplicate record creation.
Is this an expected behavior with nestjs ?

Note: a quick hack done to resolve by changing the local strategy verify function with the use of req.user (see below code).

async (req, email: string, password: string, done) => {
         
          if (req.user) {
            done(null, req.user);
          } else {
            try {
              const { user } = await this.authService.signUp({
                email,
                password,
                username: req.body.username
              });
              done(null, user);
            } catch (error) {
              done(error, false);
            }
          }
        }

**Comment by EndyKaufman** [comment]
thanks for this issue, solved at https://github.com/rucken/todo-nestjs/commit/94b03dc15cb6b4c60d4d4769c8790d65951cfbc8
;)
